# Generated by Django 4.0.3 on 2022-05-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='similar_users',
            field=models.ManyToManyField(to='articles.userdetails'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('articles', models.ManyToManyField(to='articles.articles')),
            ],
        ),
        migrations.AddField(
            model_name='userdetails',
            name='interests',
            field=models.ManyToManyField(to='articles.category'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='likes',
            field=models.ManyToManyField(to='articles.articles'),
        ),
    ]
