# Generated by Django 4.0.3 on 2022-05-27 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_userdetails_similar_users_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='cat',
            field=models.CharField(default='NULL', max_length=15),
        ),
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.CharField(default='NULL', max_length=1000000),
        ),
        migrations.AddField(
            model_name='articles',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='pdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.CharField(default='NULL', max_length=200),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='articles',
            name='writer',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
