# Generated by Django 4.0.3 on 2022-05-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_cat_articles_content_articles_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catid',
            field=models.IntegerField(default=0),
        ),
    ]
