# Generated by Django 4.0.3 on 2022-05-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_category_catid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='articles',
        ),
    ]
