# Generated by Django 4.0.3 on 2022-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_category_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='cat',
        ),
        migrations.AddField(
            model_name='articles',
            name='cat',
            field=models.ManyToManyField(to='articles.category'),
        ),
    ]
