# Generated by Django 4.0.3 on 2022-05-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_articles_cat_articles_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='similar_users',
        ),
        migrations.AlterField(
            model_name='articles',
            name='tags',
            field=models.CharField(default='NULL', max_length=700),
        ),
    ]
